### ISSUE TITLE
These images do not appear to work with OverlayFS

### ISSUE THREAD

**Issue by dmtucker** [jake-low/hadoop.docker#1]
On OverlayFS, the NameNode crashes immediately:
```
$ cd hadoop.docker/EXAMPLES/base-hadoop/
$ docker-compose up --build -d
Creating network "basehadoop_default" with the default driver
Creating basehadoop_namenode_1
Creating basehadoop_datanode_1
Creating basehadoop_resourcemanager_1
Creating basehadoop_nodemanager_1
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
cd3956f6ae0d        jakelow/hadoop:2    "yarn nodemanager"       32 seconds ago      Up 31 seconds                                   basehadoop_nodemanager_1
504e91b7a880        jakelow/hadoop:2    "yarn resourcemanager"   34 seconds ago      Up 32 seconds                                   basehadoop_resourcemanager_1
b0259594833f        jakelow/hadoop:2    "hdfs datanode"          34 seconds ago      Up 32 seconds                                   basehadoop_datanode_1
e2db86491e68        jakelow/hadoop:2    "hdfs namenode"          35 seconds ago      Exited (1) 30 seconds ago                       basehadoop_namenode_1
$ docker-compose logs namenode | tail -n20
namenode_1         | 2017-01-25 23:22:42,192 ERROR [main] namenode.NameNode (NameNode.java:main(1559)) - Failed to start namenode.
namenode_1         | ExitCodeException exitCode=1: 
namenode_1         | 	at org.apache.hadoop.util.Shell.runCommand(Shell.java:545)
namenode_1         | 	at org.apache.hadoop.util.Shell.run(Shell.java:456)
namenode_1         | 	at org.apache.hadoop.fs.DF.getFilesystem(DF.java:76)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeResourceChecker$CheckedVolume.<init>(NameNodeResourceChecker.java:69)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeResourceChecker.addDirToCheck(NameNodeResourceChecker.java:165)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeResourceChecker.<init>(NameNodeResourceChecker.java:134)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startCommonServices(FSNamesystem.java:1058)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.NameNode.startCommonServices(NameNode.java:678)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:664)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:811)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:795)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1488)
namenode_1         | 	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1554)
namenode_1         | 2017-01-25 23:22:42,196 INFO  [main] util.ExitUtil (ExitUtil.java:terminate(124)) - Exiting with status 1
namenode_1         | 2017-01-25 23:22:42,197 INFO  [Thread-1] namenode.NameNode (LogAdapter.java:info(47)) - SHUTDOWN_MSG: 
namenode_1         | /************************************************************
namenode_1         | SHUTDOWN_MSG: Shutting down NameNode at namenode/172.18.0.2
namenode_1         | ************************************************************/
```

A shell command is returning 1:
```
ExitCodeException exitCode=1: 
    at org.apache.hadoop.util.Shell.runCommand(Shell.java:545)
```

[That command is: `df -k -P /tmp/hadoop-hdfs/dfs/name`](https://github.com/apache/hadoop/blob/branch-2.7/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/DF.java#L144):
``` java
  @Override
  protected String[] getExecString() {
    // ignoring the error since the exit code it enough
    if (Shell.WINDOWS){
      throw new AssertionError(
          "DF.getExecString() should never be called on Windows");
    } else {
      return new String[] {"bash","-c","exec 'df' '-k' '-P' '" + dirPath 
                      + "' 2>/dev/null"};
    }
  }
```

It succeeds on AUFS:
```
$ docker-compose run namenode sh
/ $ df -k -P /tmp/hadoop-hdfs/dfs/name
Filesystem           1024-blocks    Used Available Capacity Mounted on
/dev/sda1            230467740  21918116 196819448  10% /tmp
```
It fails on OverlayFS:
```
$ docker-compose run namenode sh
/ $ df -k -P /tmp/hadoop-hdfs/dfs/name
Filesystem           1024-blocks    Used Available Capacity Mounted on
df: /tmp/hadoop-hdfs/dfs/name: can't find mount point
/ $ echo $?
1
```

This does not seem reproducable in other images:
AUFS:
```
$ docker run --rm -it alpine:latest df
Filesystem           1K-blocks      Used Available Use% Mounted on
none                 230467740  21989436 196748128  10% /
tmpfs                 20620676         0  20620676   0% /dev
tmpfs                 20620676         0  20620676   0% /sys/fs/cgroup
/dev/sda1            230467740  21989436 196748128  10% /etc/resolv.conf
/dev/sda1            230467740  21989436 196748128  10% /etc/hostname
/dev/sda1            230467740  21989436 196748128  10% /etc/hosts
shm                      65536         0     65536   0% /dev/shm
tmpfs                 20620676         0  20620676   0% /proc/kcore
tmpfs                 20620676         0  20620676   0% /proc/timer_list
tmpfs                 20620676         0  20620676   0% /proc/timer_stats
tmpfs                 20620676         0  20620676   0% /proc/sched_debug
tmpfs                 20620676         0  20620676   0% /sys/firmware
```
OverlayFS:
```
$ docker run --rm -it alpine:latest df
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay               51475068   6919296  41917948  14% /
tmpfs                  8190956         0   8190956   0% /dev
tmpfs                  8190956         0   8190956   0% /sys/fs/cgroup
/dev/mapper/fedora_dtucker--desk-root
                      51475068   6919296  41917948  14% /etc/resolv.conf
/dev/mapper/fedora_dtucker--desk-root
                      51475068   6919296  41917948  14% /etc/hostname
/dev/mapper/fedora_dtucker--desk-root
                      51475068   6919300  41917944  14% /etc/hosts
shm                      65536         0     65536   0% /dev/shm
tmpfs                  8190956         0   8190956   0% /proc/kcore
tmpfs                  8190956         0   8190956   0% /proc/latency_stats
tmpfs                  8190956         0   8190956   0% /proc/timer_list
tmpfs                  8190956         0   8190956   0% /proc/timer_stats
tmpfs                  8190956         0   8190956   0% /proc/sched_debug
tmpfs                  8190956         0   8190956   0% /sys/firmware
```

Here is info on the AUFS system (Debian) and the OverlayFS system (Fedora), respectively:
```
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 72
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 39.33 GiB
Name: dtucker-wkstn
ID: MZZ3:6SW2:47AQ:UDUK:JO3Z:R2HB:23UO:NJNC:MAER:GNDM:6OKG:74DD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
```
$ docker info
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.5.5-300.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 15.62 GiB
Name: dtucker-desk.west.isilon.com
ID: BNBO:PYTD:EQPI:7IAI:4WOZ:3QMX:CJ3Q:XN4U:V2ET:VNKR:5BXL:YBVQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by dmtucker** [comment]
This *does* reproduce with alpine:3.3 on Fedora 24 though:
```
$ docker run --rm alpine:3.3 df
Unable to find image 'alpine:3.3' locally
3.3: Pulling from library/alpine
5a026b6c4964: Pull complete 
Digest: sha256:925991fda395a81dd67f22f7d740c117fbff1bcca8ce3d4b40697263b5a11557
Status: Downloaded newer image for alpine:3.3
Filesystem 1K-blocks Used Available Use% Mounted on
$
```

Perhaps the base image just needs to be updated.

*edit*: Anything 3.4 or later seems to work.

**Comment by seanvetter** [comment]
alpine:3.3 seems to be the problem. I updated my local image to alpine:latest and everything is working correctly.
